services:
  webotp:
    container_name: webotp
    image: "ghcr.io/malonzhao/webotp:latest"
    environment:
      - ENCRYPTION_KEY=abcdefghijklmnopqrstuvwxyz123456
      - JWT_SECRET=webotp_secret_key
      - JWT_REFRESH_SECRET=webotp_refresh_secret_key
    ports:
      - "8080:8080"
    volumes:
      - ./data:/root/.otp
